// Real app and canonical temporary data. No household credentials, no HA writes.
const {chromium}=require(process.env.PILOTSUITE_PLAYWRIGHT||'playwright');
const {spawn}=require('node:child_process');
const {createInterface}=require('node:readline');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
 const root=path.resolve(__dirname,'..');
 const proc=spawn(process.env.PYTHON||'python',['scripts/compass_browser_fixture.py','--workspace'],{
  cwd:root,env:{...process.env,PYTHONPATH:path.join(root,'pilotsuite')},stdio:['pipe','pipe','pipe']});
 let stderr='',browser;proc.stderr.on('data',d=>{stderr=(stderr+d).slice(-12000);});
 const lines=createInterface({input:proc.stdout})[Symbol.asyncIterator]();
 async function read(){let timer;try{const row=await Promise.race([lines.next(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Fixture timeout '+stderr)),15000);})]);if(row.done)throw Error(stderr);return JSON.parse(row.value);}finally{clearTimeout(timer);}}
 const command=async data=>{proc.stdin.write(JSON.stringify(data)+'\n');return read();};
 try{
  const info=await read();browser=await chromium.launch({headless:true,...(process.env.PILOTSUITE_CHROMIUM?{executablePath:process.env.PILOTSUITE_CHROMIUM}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(10000);
  const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))requests.push({url:r.url(),method:r.method()});});
  // Reproduce a cached/late enhancement: canonical data can arrive before workspace.js.
  await page.route('**/assets/workspace.js',async route=>{
   await page.waitForFunction(()=>typeof contextData!=='undefined'&&contextData&&!selectionBusy);
   await route.continue();
  });
  await page.goto(info.url);
  await page.waitForFunction(()=>document.body.classList.contains('ps-workspace-ready')&&contextData&& !selectionBusy);
  assert.deepEqual(errors,[]);
  assert.equal(await page.locator('.ps-nav > a').count(),3,'exactly three primary destinations');
  assert.deepEqual(await page.locator('.ps-nav > a').allTextContents(),['Zonen','Werkzeuge','System']);
  const before=await command({action:'snapshot'});
  assert.equal(await page.locator('#ps-cockpit').isVisible(),true);
  assert.equal(await page.locator('#context-form').isVisible(),false);
  assert.equal(await page.locator('#ps-zone-grid>article').count(),2);
  assert.match(await page.locator('#ps-zone-grid').innerText(),/21,8 °C/);
  await page.locator('#ps-zone-search').fill('Arbeitszimmer');assert.equal(await page.locator('#ps-zone-grid>article').count(),1);
  await page.locator('#ps-zone-search').fill('');
  console.log('ok 1 - default cockpit uses actual zone data and filters without mutations');
  const nav=view=>({
   async click(){const link=page.locator(`[data-ps-nav="${view}"]`);if(!await link.isVisible())await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();await link.click();},
   getAttribute:name=>page.locator(`[data-ps-nav="${view}"]`).getAttribute(name)
  });
  await nav('zone').click();
  assert.equal(await page.locator('#ps-zone-diagnostics').evaluate(e=>e.open),false);
  assert.equal(await page.locator('#ps-zone-presence').isVisible(),true);
  assert.equal(await page.locator('#ps-module-grid').isVisible(),false);
  await page.locator('#ps-zone-diagnostics > summary').click();
  await page.locator('.ps-module-card').first().waitFor();
  assert.equal(await page.locator('.ps-module-card').count(),4);
  assert.equal(await page.locator('.ps-flow-node').count(),3);
  assert.match(await page.locator('#ps-module-detail').innerText(),/kein Live-Zustand/);
  await page.locator('[data-ps-module="climate"]').click();
  assert.equal(await page.locator('[data-ps-module="climate"]').evaluate(e=>e===document.activeElement),true);
  assert.match(await page.locator('#ps-module-detail').innerText(),/Raumtemperatur/);
  assert.equal(await page.locator('#ps-adoption-review').count(),0);
  assert.deepEqual(before,await command({action:'snapshot'}));
  console.log('ok 2 - module graph is source-based, keyboard focused and not an activation');
  await page.locator('[data-ps-module="lighting"]').click();
  const preLighting=await command({action:'snapshot'});
  assert.equal(requests.some(r=>r.url.includes('/lighting-preview')),false);
  assert.equal(requests.some(r=>r.url.includes('/lighting-decision')),false);
  await page.route('**/lighting-decision',async route=>{await new Promise(resolve=>setTimeout(resolve,100));await route.continue();},{times:1});
  await page.locator('#ps-lighting-decision').click();
  await page.evaluate(async()=>{await loadContext();});
  await page.waitForFunction(()=>document.getElementById('ps-lighting-decision-result').textContent.includes('Prüfergebnis wurde nicht gespeichert'));
  const decisionText=await page.locator('#ps-lighting-decision-result').innerText();
  assert.match(decisionText,/Innen-Helligkeit: 430 lx/);
  assert.match(decisionText,/1 passende Automationsstrukturen gelesen/);
  assert.match(decisionText,/Außenhelligkeit nicht bestätigt/);
  assert.match(decisionText,/weder Duplikat noch sichere Lösung/);
  assert.match(decisionText,/Regelverhalten mit Testdaten prüfen/);
  assert.deepEqual(preLighting.roles,(await command({action:'snapshot'})).roles);
  await page.locator('#ps-lighting-scenario').selectOption('daylight_transition');
  await page.locator('#ps-lighting-preview').click();
  await page.waitForFunction(()=>document.getElementById('ps-lighting-preview-result').textContent.includes('Ergebnis wurde nicht gespeichert'));
  const lightingText=await page.locator('#ps-lighting-preview-result').innerText();
  assert.match(lightingText,/Stabilisierung/);
  assert.match(lightingText,/Mindestabstand/);
  assert.match(lightingText,/Leuchten 1\/1 · Innen-Lux 1\/1 · binäre Helligkeit 0\/0/);
  assert.match(lightingText,/Innen-Lux oder Eigenlicht bestätigen keine Außenhelligkeit/);
  assert.match(lightingText,/Vorschau: Ein · 35 % · nicht ausgeführt/);
  await page.locator('#ps-lighting-scenario').selectOption('daylight_recovery');
  await page.locator('#ps-lighting-preview').click();
  await page.waitForFunction(()=>document.getElementById('ps-lighting-preview-result').textContent.includes('Helligkeitsquelle fällt aus und kehrt zurück'));
  const recoverySteps=page.locator('#ps-lighting-preview-result li');
  assert.equal(await recoverySteps.count(),5);
  assert.match(await recoverySteps.nth(1).innerText(),/nach Rückkehr beginnt die Stabilitätsprüfung neu/);
  assert.match(await recoverySteps.nth(2).innerText(),/\+40 s · Stabilisierung/);
  assert.match(await recoverySteps.nth(3).innerText(),/\+69 s · Stabilisierung/);
  assert.doesNotMatch(await recoverySteps.nth(3).innerText(),/Vorschau: Ein/);
  assert.match(await recoverySteps.nth(4).innerText(),/\+70 s · Vorschlag/);
  assert.match(await recoverySteps.nth(4).innerText(),/65 % · nicht ausgeführt/);
  if(process.env.PILOTSUITE_SCREENSHOTS){
   await fs.mkdir(process.env.PILOTSUITE_SCREENSHOTS,{recursive:true});
   await page.locator('#ps-lighting-preview-result').screenshot({path:path.join(process.env.PILOTSUITE_SCREENSHOTS,'lighting-recovery.png')});
  }
  const postLighting=await command({action:'snapshot'});
  assert.equal(postLighting.related_reads,preLighting.related_reads+1);
  assert.equal(postLighting.config_reads,preLighting.config_reads+1);
  assert.deepEqual(postLighting.roles,preLighting.roles);
  assert.deepEqual(postLighting.drafts,preLighting.drafts);
  assert.deepEqual(postLighting.notes,preLighting.notes);
  assert.equal(postLighting.ha_writes,preLighting.ha_writes);
  assert.equal(postLighting.helper_writes,preLighting.helper_writes);
  await page.getByRole('button',{name:'Quellen konfigurieren',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('context-form').hidden&&!selectionBusy);
  assert.equal(await page.locator('[data-ps-role="illuminance"]').isVisible(),true);
  assert.equal(await page.locator('[data-ps-role="temperature"]').isVisible(),false);
  const chosen=await page.locator('#role-illuminance input:checked').count();
  await page.locator('[data-ps-role="illuminance"] input[type=search]').fill('no-match');
  assert.equal(await page.locator('#role-illuminance input:checked').count(),chosen);
  assert.match(await page.locator('[data-ps-role="illuminance"] .ps-role-count').innerText(),/1 ausgewählt · 0/);
  await page.locator('[data-ps-role="illuminance"] input[type=search]').fill('');
  await page.locator('#role-illuminance input').uncheck();
  assert.match(await page.locator('#ps-config-diff').innerText(),/Helligkeit \(Lux\)/);
  await nav('cockpit').click();assert.equal(await page.locator('#context-form').isVisible(),true);
  assert.match(await page.locator('#ps-notice').innerText(),/speichern oder abbrechen/);
  assert.deepEqual(before.roles,(await command({action:'snapshot'})).roles);
  await page.locator('#context-cancel').click();await page.waitForFunction(()=>!contextEditing);
  assert.deepEqual(before.roles,(await command({action:'snapshot'})).roles);
  console.log('ok 3 - source search, diff and navigation guard preserve unsaved selections');
  await page.locator('#context-edit').click();await page.waitForFunction(()=>!byId('context-form').hidden&&!selectionBusy);
  await page.locator('.ps-role-filters button').first().click();
  await page.locator('#role-illuminance input').uncheck();
  await page.locator('#context-form button[type=submit]').click();
  await page.waitForFunction(()=>!contextEditing&&!selectionBusy);
  const saved=await command({action:'snapshot'});
  assert.deepEqual(saved.roles.illuminance,[]);assert.deepEqual(saved.roles.presence,before.roles.presence);assert.equal(saved.learning,before.learning);assert.equal(saved.ha_writes,0);assert.equal(saved.helper_writes,0);
  console.log('ok 4 - explicit form save uses existing revision and consent owner');
  await nav('zone').click();await page.locator('[data-ps-module="presence"]').click();
  const preReplay=await command({action:'snapshot'});
  assert.equal(requests.some(r=>r.url.includes('/presence-runtime/replay')),false);
  await page.locator('#ps-presence-scenario').selectOption('restart_during_grace');
  await page.locator('#ps-presence-replay').click();
  await page.waitForFunction(()=>document.getElementById('ps-presence-replay-result').textContent.includes('Ergebnis wurde nicht gespeichert'));
  assert.equal(await page.locator('#ps-presence-scenario').inputValue(),'restart_during_grace');
  const replayText=await page.locator('#ps-presence-replay-result').innerText();
  assert.match(replayText,/bestehende Nachlauf bleibt unverändert/);
  assert.match(replayText,/\+311 s · Frei/);
  assert.match(replayText,/nicht ausgeführt/);
  assert.deepEqual(preReplay,await command({action:'snapshot'}));
  const preReview=await command({action:'snapshot'});
  await page.locator('#ps-adoption-review').click();
  await page.waitForFunction(()=>document.getElementById('ps-review-result').textContent.includes('verwandte Automationen'));
  assert.equal((await command({action:'snapshot'})).config_reads,preReview.config_reads+1);
  assert.match(await page.locator('#ps-review-result').innerText(),/kein Nachweis für Konfliktfreiheit/);
  assert.doesNotMatch(await page.locator('#ps-review-result').innerText(),/PRIVATE_CONFIG_CANARY/);
  await page.route('**/api/v1/zones/a/context',route=>route.fulfill({status:503,json:{message:'synthetic offline'}}),{times:1});
  await page.evaluate(async()=>{try{await loadContext();}catch{}renderLearning();});
  assert.equal(await page.locator('.ps-module-card').count(),0);
  await page.evaluate(async()=>{await loadContext();});await page.locator('.ps-module-card').first().waitFor();
  console.log('ok 5 - synthetic replay, structural review and failed reads do not imply authority');
  // Names stay plain text in cards and the dependency view.
  await page.evaluate(()=>{zoneDefinitions[0].name='<img src=x onerror="window.workspaceCanary=1">';renderZoneView();});
  assert.equal(await page.locator('#ps-zone-grid img').count(),0);assert.equal(await page.evaluate(()=>window.workspaceCanary),undefined);
  await page.evaluate(async()=>{await load();});
  await nav('history').click();assert.equal(await page.locator('#history-section').isVisible(),true);
  assert.equal(requests.some(r=>r.url.includes('/history')),false);
  await nav('system').click();await page.locator('#ps-theme').selectOption('dark');await page.locator('#ps-density').selectOption('compact');await page.locator('#ps-show-ids').check();
  const prefs=await page.evaluate(()=>JSON.parse(localStorage.getItem('pilotsuite.workspace.v1')));
  assert.deepEqual(Object.keys(prefs).sort(),['density','ids','theme','view']);
  await page.reload();await page.waitForFunction(()=>document.body.classList.contains('ps-workspace-ready')&&contextData&&!selectionBusy);
  assert.equal(await page.locator('html').getAttribute('data-ps-theme'),'dark');
  assert.equal(await page.locator('html').getAttribute('data-ps-density'),'compact');
  assert.equal(await page.locator('#ps-density').inputValue(),'compact');
  console.log('ok 6 - no automatic recorder reads; display preferences survive reload without household state');
  await command({action:'comparison_fixture'});
  await page.evaluate(async()=>{await load();});
  await nav('zone').click();
  // Fixture changed canonical roles/revision outside this browser session. A partial
  // dashboard refresh must not validate its stale entity-selection basis.
  assert.equal(await page.locator('.ps-module-card').count(),0);
  await page.locator('#ps-zone-diagnostics > summary').click();
  assert.match(await page.locator('#ps-module-grid').innerText(),/Zonenstand nicht bestätigt/);
  // Explicit browser reload re-reads both inventory and context through the real app.
  await page.reload();
  await page.waitForFunction(()=>contextData&&!selectionBusy&&
    selectionDraft?.inventory?.revision===contextData.revision);
  await page.locator('#ps-zone-diagnostics > summary').click();
  await page.locator('[data-ps-module="climate"]').click();
  assert.match(await page.locator('#ps-module-detail').innerText(),/Automatisch abgeleitet/);
  assert.match(await page.locator('#ps-temperature-comparison').innerText(),/10 °C/);
  assert.match(await page.locator('#ps-temperature-comparison').innerText(),/11,8 °C/);
  assert.equal(Object.hasOwn((await command({action:'snapshot'})).roles,'temperature'),false);
  assert.match(await page.locator('[data-ps-module="climate"]').innerText(),/4 zugeordnet · 4 aktuell nutzbar/);
  await nav('config').click();await page.locator('#context-edit').click();
  await page.waitForFunction(()=>!byId('context-form').hidden&&!selectionBusy);
  assert.equal(await page.locator('#role-temperature input:checked').count(),1);
  await page.locator('#context-form button[type=submit]').click();
  await page.waitForFunction(()=>!contextEditing&&!selectionBusy);
  assert.equal(Object.hasOwn((await command({action:'snapshot'})).roles,'temperature'),false);
  await nav('zone').click();await page.locator('[data-ps-module="climate"]').click();
  await command({action:'comparison_unavailable'});
  await page.evaluate(async()=>{await load();});
  assert.match(await page.locator('#ps-temperature-comparison').innerText(),/Nicht verfügbar/);
  assert.doesNotMatch(await page.locator('#ps-temperature-comparison').innerText(),/Zone minus Vergleich/);
  assert.equal((await command({action:'snapshot'})).ha_writes,0);
  console.log('ok 6b - derived roles agree with usable sources; optional comparison is separate and invalidates');
  const out=process.env.PILOTSUITE_SCREENSHOTS;
  if(out)await fs.mkdir(out,{recursive:true});
  for(const width of [390,768,1440]){
   await page.setViewportSize({width,height:1100});
   await nav('system').click();await page.locator('#ps-density').selectOption('comfortable');
   for(const theme of ['light','dark']){
    await page.locator('#ps-theme').selectOption(theme);
    await nav('cockpit').click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`cockpit overflow ${width}`);
    if(out)await page.screenshot({path:path.join(out,`workspace-cockpit-${theme}-${width}.png`),fullPage:true});
    await nav('zone').click();await page.locator('[data-ps-module="climate"]').click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`module overflow ${width}`);
    if(out)await page.screenshot({path:path.join(out,`workspace-modules-${theme}-${width}.png`),fullPage:true});
    await nav('system').click();
   }
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  await nav('config').click();await page.locator('#context-edit').click();await page.waitForFunction(()=>!contextEditing||(!byId('context-form').hidden&&!selectionBusy));
  await page.locator('.ps-role-filters button').first().click();
  if(out)await page.screenshot({path:path.join(out,'workspace-config-1440.png'),fullPage:true});
  await page.locator('#context-cancel').click();
  await page.evaluate(()=>{location.hash='#pattern-workbench';});
  await page.locator('#pattern-workbench').waitFor({state:'visible'});
  assert.equal(await nav('workbench').getAttribute('aria-current'),'page');
  assert.deepEqual(errors,[]);
  const end=await command({action:'snapshot'});assert.equal(end.ha_writes,0);assert.equal(end.helper_writes,0);
  const replayRequests=requests.filter(r=>r.url.includes('/presence-runtime/replay'));
  assert.equal(replayRequests.length,1);assert.equal(replayRequests[0].method,'POST');
  const lightingRequests=requests.filter(r=>r.url.includes('/lighting-preview'));
  assert.equal(lightingRequests.length,2);assert.ok(lightingRequests.every(r=>r.method==='POST'));
  const decisionRequests=requests.filter(r=>r.url.includes('/lighting-decision'));
  assert.equal(decisionRequests.length,1);assert.equal(decisionRequests[0].method,'POST');
  assert.equal(requests.some(r=>(r.url.includes('/presence-runtime')&&!r.url.includes('/presence-runtime/replay'))||/helpers\/provision|transactions\/.+\/apply/.test(r.url)),false);
  console.log('ok 7 - mobile/tablet/desktop themes, deep links, reduced motion and no control calls');
 }finally{if(browser)await browser.close();proc.stdin.end();proc.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
