// Actual HTTP/store/application; fake HA only. No household credentials or writes.
const {chromium}=require(process.env.PILOTSUITE_PLAYWRIGHT||'playwright');
const {spawn}=require('node:child_process'),{createInterface}=require('node:readline');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
(async()=>{
 const root=path.resolve(__dirname,'..'),proc=spawn(process.env.PYTHON||'python',['scripts/zone_instance_browser_fixture.py'],{cwd:root,env:{...process.env,PYTHONPATH:path.join(root,'pilotsuite')},stdio:['pipe','pipe','pipe']});
 let stderr='',browser;proc.stderr.on('data',d=>stderr=(stderr+d).slice(-5000));const lines=createInterface({input:proc.stdout})[Symbol.asyncIterator]();
 async function read(){let timer;try{const r=await Promise.race([lines.next(),new Promise((_,reject)=>timer=setTimeout(()=>reject(Error(stderr||'fixture timeout')),15000))]);if(r.done)throw Error(stderr);return JSON.parse(r.value);}finally{clearTimeout(timer);}}
 const command=async c=>{proc.stdin.write(JSON.stringify(c)+'\n');return read();};
 try{
  const info=await read();browser=await chromium.launch({headless:true,...(process.env.PILOTSUITE_CHROMIUM?{executablePath:process.env.PILOTSUITE_CHROMIUM}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(10000);const errors=[],network=[];let dialogCount=0;
  await page.emulateMedia({reducedMotion:'reduce'});
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{dialogCount++;d.accept();});page.on('request',r=>{if(r.method()!=='GET')network.push({method:r.method(),url:r.url()});});
  await page.clock.setFixedTime(new Date(info.now*1000));await page.goto(info.url);
  await page.waitForFunction(()=>contextData&&!selectionBusy);
  await page.locator('#ps-zone-configure:not([disabled])').waitFor();
  assert.equal(await page.locator('.ps-nav > a').count(),3);
  assert.equal(await page.locator('#ps-zone-diagnostics').evaluate(e=>e.open),false);
  assert.equal(await page.locator('#ps-module-grid').isVisible(),false);
  assert.equal(await page.locator('#ps-presence-state strong').textContent(),'Belegt');
  assert.equal(await page.locator('#ps-presence-publication strong').textContent(),'Nicht eingerichtet');
  assert.match(await page.locator('#ps-presence-state').innerText(),/PilotSuite-Bewertung/);
  assert.equal(await page.locator('#ps-helper-options').evaluate(e=>e.open),false);
  await page.locator('#ps-zone-diagnostics > summary').click();
  await page.locator('[data-ps-module="climate"]').click();
  assert.equal(await page.locator('#ps-zone-presence').isVisible(),true,'presence is independent of diagnostic module');
  await page.locator('#ps-zone-diagnostics > summary').click();
  assert.deepEqual(errors,[]);const baseline=await command({action:'snapshot'});assert.equal(baseline.learning,false);assert.equal(baseline.view.current.state,'occupied');
  assert.equal(baseline.helper_creates,0);assert.equal(baseline.output_calls,0);
  const out=process.env.PILOTSUITE_SCREENSHOTS;if(out){await fs.mkdir(out,{recursive:true});await page.screenshot({path:path.join(out,'zone-presence-first-desktop.png'),fullPage:true});}
  assert.equal(baseline.zones.length,4);
  for(const [zone,expected] of [['z_empty','Unklar'],['z_paused','Pausiert'],['z_other','Unklar'],['room','Belegt']]){
   await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
   assert.equal(await page.locator('#ps-zone-grid>article').count(),4);
   await page.locator(`[data-ps-zone="${zone}"]`).click();
   await page.waitForFunction(value=>document.querySelector('#ps-presence-state strong')?.textContent===value,expected);
   assert.equal(await page.locator('#ps-view-title').evaluate(e=>e===document.activeElement),true);
  }
  assert.deepEqual((await command({action:'snapshot'})).zones,baseline.zones);
  assert.equal(network.length,0,'zone navigation performs no POST, PUT or HA write');
  await page.locator('[data-ps-live="sources"] summary').click();
  const passive=await page.evaluate(async()=>{
    window.scrollTo(0,450);
    const before=document.scrollingElement.scrollTop,button=document.getElementById('ps-zone-configure'),context=contextData;
    await load({background:true});await load({background:true});
    return {before,after:document.scrollingElement.scrollTop,buttonRetained:button===document.getElementById('ps-zone-configure'),contextRetained:context===contextData,sourcesOpen:document.querySelector('[data-ps-live="sources"]').open};
  });
  assert.equal(passive.after,passive.before);assert.equal(passive.buttonRetained,true);
  assert.equal(passive.contextRetained,true);assert.equal(passive.sourcesOpen,true);
  console.log('ok 0 - passive refresh retains reading position, controls, context and open sources');
  const refreshPresence=()=>page.locator('#ps-zone-presence').getByRole('button',{name:'Aktualisieren',exact:true}).click();
  await command({action:'tick',values:{'binary_sensor.demo_presence':'unavailable','binary_sensor.demo_motion':'unavailable'}});await refreshPresence();
  await page.waitForFunction(()=>document.querySelector('#ps-presence-state strong')?.textContent==='Unklar');
  assert.match(await page.locator('#ps-zone-presence').innerText(),/erforderliche Quelle\(n\) derzeit nicht nutzbar/);
  await command({action:'tick',values:{'binary_sensor.demo_presence':'on','binary_sensor.demo_motion':'off'}});await refreshPresence();
  await page.waitForFunction(()=>document.querySelector('#ps-presence-state strong')?.textContent==='Belegt');
  await page.route('**/api/v1/zones/room/presence',route=>route.fulfill({status:503,json:{message:'Synthetic connection failure'}}),{times:1});
  await refreshPresence();await page.locator('#ps-zone-configure[disabled]').waitFor();
  assert.match(await page.locator('#ps-zone-presence').innerText(),/Unklar bedeutet nicht frei/);
  assert.equal(await page.locator('#ps-presence-state').count(),0,'failed read removes the old decision');
  await refreshPresence();await page.locator('#ps-zone-configure:not([disabled])').waitFor();
  await page.evaluate(()=>{location.hash='#ps-module-detail';});
  await page.waitForFunction(()=>document.getElementById('ps-zone-diagnostics').open);
  await page.locator('#ps-zone-diagnostics > summary').focus();await page.keyboard.press('Enter');
  assert.equal(await page.locator('#ps-zone-diagnostics').evaluate(e=>e.open),false);
  console.log('ok 0b - required source gaps, failed reads and keyboard/direct-link recovery stay explicit');
  await page.locator('#ps-helper-options>summary').click();
  await page.route('**/api/v1/zones/room/presence/package',route=>route.fulfill({status:503,json:{message:'Synthetic package preview failure'}}),{times:1});
  await page.locator('#ps-zone-prepare').click();
  await page.getByText('Synthetic package preview failure',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Schließen',exact:true}).click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  assert.equal((await command({action:'snapshot'})).helper_creates,0);
  await page.locator('#ps-helper-options>summary').click();
  console.log('ok 0c - failed helper preview can be closed without creation, retry or trapped editor');
  await page.locator('#ps-helper-options>summary').click();
  await page.locator('#ps-helper-single').click();
  await page.getByLabel('Fehlende Funktion',{exact:true}).selectOption('presence_timer');
  await page.getByLabel('Timerdauer (Sekunden)',{exact:true}).fill('240');
  await page.evaluate(async()=>{await load({background:true});await load({background:true});});
  assert.equal(await page.getByLabel('Timerdauer (Sekunden)',{exact:true}).inputValue(),'240');
  await page.getByRole('button',{name:'Einzelhelfer-Plan prüfen',exact:true}).click();
  await page.getByRole('button',{name:'Diesen einzelnen Helfer anlegen',exact:true}).waitFor();
  assert.match(await page.locator('#ps-zone-presence').innerText(),/240 Sekunden/);
  assert.match(await page.locator('#ps-zone-presence').innerText(),/Steuerungsverantwortung bleiben unverändert/);
  if(out)await page.screenshot({path:path.join(out,'single-helper-preview-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Schließen',exact:true}).click();
  assert.equal((await command({action:'snapshot'})).helper_creates,0,'single-helper preview performs no HA write');
  await page.locator('#ps-helper-options>summary').click();
  await page.evaluate(()=>{location.hash='#ps-organization';});
  await page.locator('#org-load:not([disabled])').click();
  await page.locator('.org-plan-history').filter({hasText:'presence_helper'}).first().click();
  await page.getByText('Einzelhelfer-Anlageplan einschließlich gegebenenfalls geplanter Beschriftung. Kein Anschluss und keine Steuerungsübernahme.',{exact:true}).waitFor();
  assert.equal(await page.locator('#org-apply-names').count(),0,'helper plan must not enter name executor');
  await page.locator('#org-back-zone').click();
  // Gates are deterministic: no timing delay or real Home Assistant request.
  async function holdRequest(pattern,method){
   let resume,arrive;const held=new Promise(resolve=>resume=resolve),received=new Promise(resolve=>arrive=resolve);
   let intercepted=false;
   const handler=async route=>{if(route.request().method()!==method||intercepted)return route.continue();
    intercepted=true;arrive();await held;await route.continue();await page.unroute(pattern,handler);};
   await page.route(pattern,handler);return {received,resume:()=>resume()};
  }
  await page.locator('#ps-zone-configure').click();await page.locator('#ps-zone-form').waitFor();
  const guardedHash=await page.evaluate(()=>location.hash);
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();assert.equal(await page.locator('#ps-zone-form').isVisible(),true);
  assert.match(await page.locator('#ps-notice').innerText(),/Bearbeitung läuft/);
  const saveGate=await holdRequest('**/api/v1/zones/room/presence','PUT');
  const reloadGate=await holdRequest('**/api/v1/selections/room','GET');
  await page.getByRole('button',{name:'Konfiguration speichern',exact:true}).click();
  await saveGate.received;
  assert.equal(await page.locator('#ps-notice').isVisible(),true,'pending save retains the guard');
  saveGate.resume();await reloadGate.received;
  assert.equal(await page.locator('#ps-notice').isVisible(),true,'pending canonical reload retains the guard');
  reloadGate.resume();
  await page.locator('#ps-zone-form').waitFor({state:'hidden'});await page.locator('#ps-zone-configure:not([disabled])').waitFor();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  assert.equal(await page.locator('#ps-notice').isVisible(),false,'completed save clears only the obsolete navigation guard');
  assert.equal(await page.evaluate(()=>location.hash),guardedHash,'completion never resumes blocked navigation');
  if(out)await page.screenshot({path:path.join(out,'zone-edit-complete-desktop.png'),fullPage:true});
  assert.equal((await command({action:'snapshot'})).mode,'compare');console.log('ok 1 - relevance-based presence, typed configuration, no extra grant, dirty guard');
  await command({action:'tick',values:{'binary_sensor.demo_presence':'off'}});await refreshPresence();
  await page.waitForFunction(()=>document.querySelector('#ps-presence-state strong')?.textContent==='Nachlauf');
  const grace=await command({action:'snapshot'});assert.equal(grace.view.current.state,'grace');
  await page.locator('#ps-zone-configure').click();await page.locator('#ps-zone-form').waitFor();
  await page.getByRole('button',{name:'Konfiguration speichern',exact:true}).click();
  await page.locator('#ps-zone-form').waitFor({state:'hidden'});
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  const sameGrace=await command({action:'snapshot'});
  assert.equal(sameGrace.view.revision,grace.view.revision,'unchanged form save keeps revision');
  assert.deepEqual(sameGrace.view.current,grace.view.current,'unchanged form save preserves the running deadline and evidence');
  for(const key of ['zones','roles','learning','organization','helper_creates','output_calls','metadata_calls'])assert.deepEqual(sameGrace[key],grace[key],key+' unchanged by identical save');
  await command({action:'tick',values:{'binary_sensor.demo_presence':'on'}});await refreshPresence();
  await page.waitForFunction(()=>document.querySelector('#ps-presence-state strong')?.textContent==='Belegt');
  console.log('ok 1c - unchanged form save retains running grace, revision and all four zones; zero HA writes');
  const beforeNotices=await command({action:'snapshot'});
  await page.locator('#ps-zone-configure').click();await page.locator('#ps-zone-form').waitFor();
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  const rejectSave=async route=>route.request().method()==='PUT'
   ?route.fulfill({status:503,json:{message:'Synthetic save failure'}}):route.continue();
  await page.route('**/api/v1/zones/room/presence',rejectSave);
  await page.getByRole('button',{name:'Konfiguration speichern',exact:true}).click();
  await page.getByText('Synthetic save failure',{exact:true}).waitFor();
  assert.equal(await page.locator('#ps-zone-form').isVisible(),true,'failed save retains the draft');
  assert.match(await page.locator('#ps-notice').innerText(),/Bearbeitung läuft/);
  await page.unroute('**/api/v1/zones/room/presence',rejectSave);
  await page.getByRole('button',{name:'Verwerfen',exact:true}).click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  assert.equal(await page.locator('#ps-notice').isVisible(),false,'discard clears an obsolete guard');
  // A second canonical editor can still own the global guard after this one closes.
  await page.locator('#ps-zone-configure').click();await page.locator('#ps-zone-form').waitFor();
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  await page.evaluate(()=>{contextEditing=true;});
  await page.getByRole('button',{name:'Verwerfen',exact:true}).click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  assert.equal(await page.locator('#ps-notice').isVisible(),true,'another draft still owns the guard');
  await page.evaluate(()=>{contextEditing=false;renderSelection();renderLearning();});
  assert.equal(await page.locator('#ps-notice').isVisible(),false,'last editor settling clears the guard');
  await page.locator('#ps-zone-configure').click();await page.locator('#ps-zone-form').waitFor();
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  await page.evaluate(()=>text('context-message','Synthetic unrelated error: Bearbeitung läuft'));
  await page.getByRole('button',{name:'Verwerfen',exact:true}).click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  assert.equal(await page.locator('#ps-notice').innerText(),'Synthetic unrelated error: Bearbeitung läuft','message ownership, not matching words, controls cleanup');
  await page.evaluate(()=>text('context-message','')); // Remove only the test-injected context error.
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();await page.locator('[data-ps-nav="zone"]').click();
  await page.locator('#ps-zone-configure:not([disabled])').waitFor();
  await page.getByRole('button',{name:'Sensordaten & Verläufe',exact:true}).click();
  await page.getByText(/aufgezeichnete Punkte ausgewertet/).waitFor();
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  assert.equal(await page.locator('#ps-notice').isVisible(),true);
  await page.getByRole('button',{name:'Ansicht schließen',exact:true}).click();
  assert.equal(await page.locator('#ps-notice').isVisible(),false,'closing a read-only editor settles its guard without polling');
  const afterNotices=await command({action:'snapshot'});
  for(const key of ['mode','roles','zones','learning','helper_creates','output_calls','metadata_calls','organization'])assert.deepEqual(afterNotices[key],beforeNotices[key],key+' unchanged by guard cleanup');
  console.log('ok 1a - save/reload gates, failed save, cancel, other draft, unrelated error and read-only close');
  await page.locator('#ps-existing-connect').click();await page.locator('#org-load').click();
  await page.locator('#org-save').waitFor();
  await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Raumstatus / interner Boolean im gesamten Bestand suchen');
  assert.equal(await page.locator('#org-helpers').evaluate(e=>e.open),true,'presence entry opens the existing helper editor');
  assert.equal(await page.getByLabel('Raumstatus / interner Boolean im gesamten Bestand suchen',{exact:true}).evaluate(e=>e===document.activeElement),true);
  await page.locator('[data-org-group=presence_automations]>summary').click();
  for(const [role,eid] of [['presence_status','input_boolean.existing_presence'],['presence_timer','timer.existing_presence'],['presence_output','binary_sensor.existing_presence'],['presence_automations','automation.existing_presence']]){
   await page.locator(`[data-org-role="${role}"][data-org-candidate="${eid}"]`).click();
  }
  await page.locator('#org-timing').selectOption('timer');
  await page.locator('#org-save').click();await page.getByText('Funktionszuordnung gespeichert und erneut geladen. Keine Haussteuerung aktiviert.',{exact:true}).waitFor();
  await page.locator('#org-back-zone').click();
  await page.locator('#ps-existing-review:not([disabled])').waitFor();
  const bound=await command({action:'snapshot'});
  assert.equal(bound.organization.assignments.presence_output[0].entity_id,'binary_sensor.existing_presence');
  assert.equal(bound.mode,'compare');assert.equal(bound.helper_creates,0);assert.equal(bound.output_calls,0);assert.equal(bound.automation_reads,0);
  await command({action:'tick'});await refreshPresence(); // Explicit synthetic worker cycle after revision change.
  await page.waitForFunction(()=>document.querySelector('#ps-existing-comparison')?.textContent.includes('Übereinstimmung'));
  assert.equal(await page.locator('#ps-presence-state strong').textContent(),'Anwesenheit gemeldet');
  assert.equal(await page.locator('[data-ps-live=calculation]').evaluate(e=>e.open),false,'comparison is secondary to existing HA status');
  assert.equal(await page.locator('#ps-presence-calculation strong').textContent(),'Belegt');
  assert.match(await page.locator('#ps-presence-state').innerText(),/Bestandsmeldung/);
  const reviewGate=await holdRequest('**/api/v1/zones/room/presence-adoption/review','POST');
  await page.locator('#ps-existing-review').click();await reviewGate.received;
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  assert.equal(await page.locator('#ps-notice').isVisible(),true,'pending read-only review retains its guard');
  reviewGate.resume();
  await page.locator('[data-existing-automation="automation.existing_consumer"]').waitFor();
  assert.equal(await page.locator('#ps-notice').isVisible(),false,'completed review settles its guard');
  assert.match(await page.locator('[data-existing-automation="automation.existing_consumer"]').innerText(),/Verwendet den Bestandsstatus/);
  assert.match(await page.locator('[data-existing-automation="automation.existing_presence"]').innerText(),/schaltet Raumstatus.*schaltet Nachlauf/s);
  assert.match(await page.locator('[data-existing-automation="automation.existing_presence"]').innerText(),/Weiterverwendung als bestehende Steuerung/);
  assert.match(await page.locator('[data-existing-automation="automation.existing_consumer"]').innerText(),/Bestehenden Verbraucher erhalten/);
  assert.equal(await page.locator('#ps-existing-reuse li').count(),6);
  assert.match(await page.locator('#ps-existing-reuse').innerText(),/Keine Konfigurationsänderung vorgeschlagen oder ausgeführt/);
  assert.match(await page.locator('#ps-existing-reuse').innerText(),/Steuerungsübergabe sind hier noch nicht ausführbar/);
  assert.equal(await page.locator('#ps-existing-reuse button').count(),0,'review has no hidden apply action');
  assert.equal((await command({action:'snapshot'})).automation_reads,2);
  await refreshPresence();assert.equal((await command({action:'snapshot'})).automation_reads,2,'polling never rereads automation configs');
  await command({action:'tick',values:{'binary_sensor.existing_presence':'unavailable'}});await refreshPresence();
  await page.waitForFunction(()=>document.querySelector('[data-existing-role="sensor"] strong')?.textContent==='Unklar');
  assert.equal(await page.locator('#ps-presence-state strong').textContent(),'Unklar','no fallback to on Boolean or occupied calculation');
  assert.match(await page.locator('#ps-existing-comparison').innerText(),/Nicht beurteilbar/);
  await command({action:'tick',values:{'binary_sensor.existing_presence':'off'}});await refreshPresence();
  await page.waitForFunction(()=>document.querySelector('#ps-existing-comparison')?.textContent.includes('Abweichung'));
  assert.equal(await page.locator('#ps-presence-state strong').textContent(),'Frei gemeldet');
  assert.equal(await page.locator('#ps-presence-calculation strong').textContent(),'Belegt','comparison does not replace HA report');
  assert.match(await page.locator('#ps-existing-presence').innerText(),/widersprechen sich aktuell/);
  await command({action:'tick',values:{'binary_sensor.existing_presence':'on'}});await refreshPresence();
  const compared=await command({action:'snapshot'});assert.equal(compared.helper_creates,0);assert.equal(compared.output_calls,0);assert.equal(compared.metadata_calls,0);
  assert.deepEqual(compared.organization,bound.organization,'review never changes saved bindings');
  for(const key of ['mode','roles','zones','learning'])assert.deepEqual(compared[key],bound[key],key+' unchanged by reuse review');
  if(out)await page.screenshot({path:path.join(out,'zone-existing-presence-desktop.png'),fullPage:true});
  console.log('ok 1b - existing chain binding, writer/consumer review, unavailable and mismatch; zero HA writes');
  await page.locator('[data-existing-role=timer] a').click();
  const timerSearch=page.getByLabel('Nachlauftimer im gesamten Bestand suchen',{exact:true});
  await timerSearch.waitFor();
  await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Nachlauftimer im gesamten Bestand suchen');
  assert.equal(await timerSearch.evaluate(e=>e===document.activeElement),true,'specific helper link focuses the existing role without reload');
  await timerSearch.fill('existing_presence');
  await page.evaluate(async()=>{await load({background:true});await load({background:true});});
  assert.equal(await timerSearch.inputValue(),'existing_presence');
  await page.locator('#org-back-zone').click();await page.locator('#ps-zone-configure:not([disabled])').waitFor();
  assert.deepEqual((await command({action:'snapshot'})).organization,bound.organization,'focused helper navigation changes no bindings');
  await page.getByRole('button',{name:'Sensordaten & Verläufe',exact:true}).click();
  try{await page.locator('.ps-zone-chart:visible').first().waitFor();}catch(e){throw Error('Historienansicht blieb leer: '+await page.locator('#ps-zone-presence .ps-notice').first().textContent()+' / '+e.message);}assert.equal(await page.locator('.ps-zone-chart:visible').count()>0,true);
  assert.equal((await command({action:'snapshot'})).history_reads,compared.history_reads+1);
  if(out)await page.screenshot({path:path.join(out,'zone-data-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Ansicht schließen',exact:true}).click();
  console.log('ok 2 - real data endpoint, recorded history charts and tables without consent step');
  await page.locator('#ps-helper-options>summary').click();
  assert.match(await page.locator('#ps-helper-options').innerText(),/Kein einzelner Ersatzhelfer/);
  await page.getByRole('button',{name:'Eigenen Anwesenheitssensor vorbereiten',exact:true}).click();
  await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).waitFor();
  assert.equal(await page.locator('.ps-package-change').count(),5);
  assert.match(await page.locator('#ps-zone-presence').innerText(),/Bestehende Zuordnung bleibt erhalten/);
  assert.equal((await command({action:'snapshot'})).helper_creates,0);
  await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).click();
  await page.getByText('Planstatus: verified',{exact:true}).waitFor();
  const created=await command({action:'snapshot'});assert.equal(created.helper_creates,5);assert.equal(created.output_calls,0);assert.equal(created.metadata_calls,1);
  await page.getByRole('button',{name:'Schließen',exact:true}).last().click();
  await page.locator('#refresh').click();await page.locator('#ps-zone-configure[disabled]').waitFor();await page.getByRole('button',{name:'Jetzt abgleichen',exact:true}).waitFor();await page.locator('#ps-zone-configure:not([disabled])').waitFor();
  console.log('ok 3 - reviewed owned output package creates only on explicit click, publishing remains off');
  await page.getByRole('button',{name:'Entitäten → Ontologie',exact:true}).click();
  await page.getByLabel('Anzeigename',{exact:true}).fill('Demo · Präsenz');await page.getByLabel('Logische Zonenmitgliedschaft',{exact:true}).selectOption('zone');await page.getByLabel('Habitus Übersicht',{exact:true}).check();
  await page.getByRole('button',{name:'Änderungsplan prüfen',exact:true}).click();await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).click();
  await page.getByText('Planstatus: verified',{exact:true}).waitFor();assert.equal((await command({action:'snapshot'})).metadata_calls,created.metadata_calls+1);
  await page.getByRole('button',{name:'Rücknahme prüfen',exact:true}).click();await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).click();
  await page.getByText('Planstatus: verified',{exact:true}).waitFor();assert.equal((await command({action:'snapshot'})).metadata_calls,created.metadata_calls+2);
  await page.getByRole('button',{name:'Schließen',exact:true}).last().click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  console.log('ok 4 - name/ontology preview, exact apply and explicit rollback');
  await page.locator('#ps-zone-configure').click();await page.locator('#ps-zone-form').waitFor();
  await page.getByLabel('Betriebsmodus',{exact:true}).selectOption('publish');
  const beforePublishDialogs=dialogCount;
  assert.match(await page.locator('#ps-presence-config-effect').innerText(),/öffentlichen Sensor|öffentliche Sensor/);
  assert.match(await page.locator('#ps-presence-config-effect').innerText(),/Verknüpfte HA-Automationen/);
  await page.getByRole('button',{name:'Konfiguration speichern',exact:true}).click();
  await page.locator('#ps-zone-form').waitFor({state:'hidden'});await page.locator('#ps-zone-configure:not([disabled])').waitFor();
  await command({action:'tick',seconds:1,values:{'binary_sensor.demo_presence':'on'}});
  assert.equal(dialogCount,beforePublishDialogs,'visible effect preview replaces redundant generic confirmation');
  const published=await command({action:'publish'});assert.equal(published.view.publication,'verified');
  const checkedAt=published.view.publication_checked_at;assert.equal(typeof checkedAt,'number');
  await refreshPresence();await page.locator('[data-ps-live=calculation]>summary').click();
  await page.getByText('Zuletzt bestätigt',{exact:true}).waitFor();
  await page.locator('#ps-zone-configure').click();await page.locator('#ps-zone-form').waitFor();
  await page.getByRole('button',{name:'Konfiguration speichern',exact:true}).click();
  await page.locator('#ps-zone-form').waitFor({state:'hidden'});
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  const samePublished=await command({action:'snapshot'});
  assert.equal(samePublished.view.revision,published.view.revision);
  assert.equal(samePublished.view.publication,'verified');
  assert.equal(samePublished.view.publication_checked_at,checkedAt,'identical save does not renew readback evidence');
  assert.equal(samePublished.output_calls,published.output_calls,'identical save does not invalidate output');
  const proofHint=await page.locator('#ps-presence-publication small').textContent();assert.match(proofHint,/Rückleseprüfung:/);
  for(let i=0;i<3;i++){
   await command({action:'tick',seconds:5});const unchanged=await command({action:'publish'});
   assert.equal(unchanged.output_calls,published.output_calls,'unchanged ticks cause no extra output write');
   assert.equal(unchanged.view.publication_checked_at,checkedAt,'passive checks never re-date evidence');
   await refreshPresence();assert.equal(await page.locator('#ps-presence-publication strong').textContent(),'Zuletzt bestätigt');
   assert.equal(await page.locator('#ps-presence-publication small').textContent(),proofHint);
  }
  if(out)await page.screenshot({path:path.join(out,'zone-publication-proof-desktop.png'),fullPage:true});
  console.log('ok 4b - dated publication proof survives unchanged ticks without extra mocked HA writes');
  for(const width of [390,768,1440]){await page.setViewportSize({width,height:1100});for(const theme of ['dark','light']){
   await page.locator('.ps-nav [data-ps-nav="system"]').click();await page.locator('#ps-theme').selectOption(theme);await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();await page.locator('[data-ps-nav="zone"]').click();
   await page.locator('#ps-zone-configure:not([disabled])').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'overflow '+width);
   if(out){
    await page.screenshot({path:path.join(out,`zone-instance-${theme}-${width}.png`),fullPage:true});
    if(width===390){if(!await page.locator('[data-ps-live=calculation]').evaluate(e=>e.open))await page.locator('[data-ps-live=calculation]>summary').click();
     await page.locator('#ps-presence-publication').evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));
     await page.locator('#ps-presence-publication').screenshot({path:path.join(out,`zone-publication-proof-mobile-${theme}.png`)});}
   }
  }}
  // A second, unlike zone has no saved PilotSuite presence configuration. A
  // helper is still creatable there, but it must not become a presence output.
  const beforeSingles=await command({action:'snapshot'});
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  await page.locator('[data-ps-zone="z_other"]').click();
  await page.waitForFunction(()=>selectionZone==='z_other'&&!selectionBusy&&document.querySelector('#ps-zone-configure')?.disabled===false);
  if(!await page.locator('#ps-helper-options').evaluate(e=>e.open))await page.locator('#ps-helper-options>summary').click();
  await page.locator('#ps-helper-single').click();
  assert.equal(await page.getByLabel('Fehlende Funktion',{exact:true}).evaluate(e=>e===document.activeElement),true);
  await page.getByLabel('Fehlende Funktion',{exact:true}).selectOption('presence_timer');
  await page.getByLabel('Timerdauer (Sekunden)',{exact:true}).fill('240');
  await page.getByRole('button',{name:'Einzelhelfer-Plan prüfen',exact:true}).click();
  await page.getByRole('button',{name:'Diesen einzelnen Helfer anlegen',exact:true}).waitFor();
  for(const width of [390,768,1440]){await page.setViewportSize({width,height:1100});for(const theme of ['light','dark']){
   await page.evaluate(theme=>document.documentElement.dataset.psTheme=theme,theme);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'helper preview overflow '+width);
   if(out)await page.screenshot({path:path.join(out,`single-helper-${theme}-${width}.png`),fullPage:true});
  }}
  await page.getByRole('button',{name:'Diesen einzelnen Helfer anlegen',exact:true}).click();
  await page.getByRole('heading',{name:'Helferanlage bestätigt · Anschluss noch offen',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Diesen einzelnen Helfer anlegen',exact:true}).count(),0);
  const afterSingle=await command({action:'snapshot'});
  assert.equal(afterSingle.helper_creates,beforeSingles.helper_creates+1);
  for(const key of ['output_calls','metadata_calls','organization','roles','learning','mode','zones'])assert.deepEqual(afterSingle[key],beforeSingles[key]);
  await page.getByRole('button',{name:'Schließen',exact:true}).click();
  await page.locator('#ps-zone-refresh:not([disabled])').click();
  assert.equal(await page.locator('#ps-presence-state strong').textContent(),'Unklar');
  await page.locator('#ps-helper-single').click();
  await page.getByLabel('Fehlende Funktion',{exact:true}).selectOption('presence_timer');
  await page.getByLabel('Timerdauer (Sekunden)',{exact:true}).fill('240');
  await page.getByRole('button',{name:'Einzelhelfer-Plan prüfen',exact:true}).click();
  await page.getByText('Helferkennung existiert bereits; vorhandenen Plan oder Bestand prüfen',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('Timerdauer (Sekunden)',{exact:true}).inputValue(),'240');
  await page.getByRole('button',{name:'Verwerfen',exact:true}).click();
  assert.equal((await command({action:'snapshot'})).helper_creates,afterSingle.helper_creates);
  console.log('ok 4c - individual helper creation in unlike zone; no binding/control, mobile themes, no duplicate, error retains draft');
  const final=await command({action:'snapshot'});assert.equal(final.learning,false);assert.deepEqual(final.roles,baseline.roles);assert.deepEqual(final.zones,baseline.zones);assert.deepEqual(errors,[]);
  assert.equal(network.some(r=>/presence-runtime|transactions\/.+\/apply|history\/import/.test(r.url)),false);
  await page.evaluate(()=>window.PilotSuiteZonePresence.invalidate());assert.equal(await page.locator('#ps-zone-configure').isDisabled(),true);
  console.log('ok 5 - themes, three widths, conservative invalidation, no legacy grants and no household calls');
  // Existing editor, one save: import explicit tag/device membership and select
  // analysis sources. Does not create or switch any HA object.
  await page.locator('[data-ps-nav="config"]').click();
  await page.locator('#zone-new').click();
  await page.locator('#zone-label-load').click();
  await page.locator('#zone-label-select:not([disabled])').waitFor();
  assert.equal(await page.locator('#zone-label-select option').filter({hasText:'Habitus Demobereich'}).count(),1,'ordinary zone labels may begin with Habitus');
  for(const role of ['Habitus Zone','Habitus Übersicht','Habitus Bedienung','Habitus Status','Habitus Konfiguration','Habitus Diagnose']){
   assert.equal(await page.locator('#zone-label-select option').evaluateAll((options,name)=>options.filter(option=>option.textContent.startsWith(name+' (')).length,role),0,'canonical role is not a zone label: '+role);
  }
  await page.locator('#zone-label-select').selectOption('setup_demo');
  await page.locator('#zone-label-import').click();
  await page.locator('.zone-member').first().waitFor();
  assert.equal(await page.locator('#zone-name').inputValue(),'Habitus Demobereich');
  const members=page.locator('.zone-member');assert.equal(await members.count(),2);
  const presence=members.filter({hasText:'binary_sensor.demo_presence'});
  await presence.getByLabel('Für Auswertung verwenden',{exact:true}).check();
  await page.locator('#zone-member-search').fill('Licht');
  await page.evaluate(async()=>{await load({background:true});await load({background:true});});
  await page.locator('#zone-member-search').fill('');
  assert.equal(await presence.getByLabel('Für Auswertung verwenden',{exact:true}).isChecked(),true);
  for(const width of [390,768,1440]){await page.setViewportSize({width,height:1100});for(const theme of ['light','dark']){
   await page.evaluate(theme=>document.documentElement.dataset.psTheme=theme,theme);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'zone import overflow '+width);
   if(out)await page.screenshot({path:path.join(out,`zone-label-setup-${theme}-${width}.png`),fullPage:true});
  }}
  const beforeSetup=await command({action:'snapshot'});
  await page.locator('#zone-form').getByRole('button',{name:'Zone speichern',exact:true}).click();
  await page.waitForFunction(()=>!zoneFormOpen&&!selectionBusy&&selectionZone.startsWith('hz_'));
  const savedSetup=await page.evaluate(()=>json('api/v1/zones/'+encodeURIComponent(selectionZone)+'/structure'));
  assert.equal(savedSetup.profile.label_id,'setup_demo');
  assert.equal(savedSetup.decisions['binary_sensor.demo_presence'],'relevant');
  assert.equal(savedSetup.decisions['light.demo'],'ignored');
  const afterSetup=await command({action:'snapshot'});
  for(const key of ['helper_creates','output_calls','metadata_calls','learning','roles','mode'])assert.deepEqual(afterSetup[key],beforeSetup[key]);
  assert.equal(afterSetup.zones.length,beforeSetup.zones.length+1);
  for(const z of beforeSetup.zones)assert.deepEqual(afterSetup.zones.find(r=>r.zone_id===z.zone_id),z);
  await page.locator('#ps-structure-sync:not([disabled])').waitFor();
  await page.locator('#ps-structure-sync').click();
  await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).waitFor();
  assert.match(await page.locator('#ps-zone-presence').innerText(),/Zonen- und Rollenlabels/);
  await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).click();
  await page.getByText('Planstatus: verified',{exact:true}).waitFor();
  const synced=await command({action:'snapshot'});
  assert.equal(synced.metadata_calls,afterSetup.metadata_calls+2);
  assert.equal(synced.output_calls,afterSetup.output_calls);
  await page.getByRole('button',{name:'Rücknahme prüfen',exact:true}).click();
  await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).click();
  await page.getByText('Planstatus: verified',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Schließen',exact:true}).click();
  assert.deepEqual(errors,[]);
  console.log('ok 6 - tag/device import and relevance in one save, explicit batch labels/readback/rollback, no actor writes');
  await page.locator('#zone-new').click();
  await page.locator('#zone-label-name').fill('Demo neuer Bereich');
  await page.locator('#zone-label-new').click();
  await page.locator('#zone-areas input[value="z_empty"]').check();
  await page.locator('#zone-extras').selectOption(['light.demo']);
  await page.locator('#zone-candidates-import').click();
  await page.locator('.zone-member').first().waitFor();
  assert.equal(await page.locator('.zone-member').count(),1);
  assert.equal(await page.locator('.zone-member').getByLabel('Für Auswertung verwenden',{exact:true}).isChecked(),false);
  for(const width of [390,768,1440]){await page.setViewportSize({width,height:1100});for(const theme of ['light','dark']){
   await page.evaluate(theme=>document.documentElement.dataset.psTheme=theme,theme);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'new label form overflow '+width);
   if(out)await page.screenshot({path:path.join(out,`zone-new-label-${theme}-${width}.png`),fullPage:true});
  }}
  const beforeNew=await command({action:'snapshot'});
  await page.locator('#zone-form').getByRole('button',{name:'Zone speichern',exact:true}).click();
  await page.waitForFunction(()=>!zoneFormOpen&&!selectionBusy&&selectionZone.startsWith('hz_'));
  const pending=await page.evaluate(()=>json('api/v1/zones/'+encodeURIComponent(selectionZone)+'/structure'));
  assert.equal(pending.profile.label_id,null);assert.equal(pending.profile.label_name,'Demo neuer Bereich');
  await page.locator('#ps-structure-sync:not([disabled])').click();
  await page.getByText('Neues HA-Zonenlabel anlegen: Demo neuer Bereich. Keine automatische Löschung bei Rücknahme.',{exact:true}).waitFor();
  assert.equal((await command({action:'snapshot'})).label_creates,beforeNew.label_creates,'preview does not create');
  await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).click();
  await page.getByText('Planstatus: verified',{exact:true}).waitFor();
  const connected=await page.evaluate(()=>json('api/v1/zones/'+encodeURIComponent(selectionZone)+'/structure'));
  assert.equal(connected.profile.label_id,'demo_neuer_bereich');assert.equal(connected.revision,pending.revision+1);
  const afterNew=await command({action:'snapshot'});
  assert.equal(afterNew.label_creates,beforeNew.label_creates+1);
  assert.equal(afterNew.metadata_calls,beforeNew.metadata_calls+1);
  assert.equal(afterNew.output_calls,beforeNew.output_calls);
  assert.equal(afterNew.helper_creates,beforeNew.helper_creates);
  await page.getByRole('button',{name:'Rücknahme prüfen',exact:true}).click();
  await page.getByRole('button',{name:'Genau diesen Plan anwenden',exact:true}).click();
  await page.getByText('Planstatus: verified',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('ok 7 - new label plus area/extra member selection, single preview/apply, durable binding and metadata rollback');
  await page.getByRole('button',{name:'Schließen',exact:true}).click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  await page.locator('.ps-zone-nav [data-ps-nav="automations"]').click();
  await page.locator('#org-load').click();
  await page.locator('.org-plan-history').first().click();
  await page.locator('#org-plan').getByText('Zonen- und Rollenlabels sowie die ausdrücklich gezeigten Anzeigenamen. Technische IDs und physische Orte bleiben erhalten.',{exact:true}).waitFor();
  assert.doesNotMatch(await page.locator('#org-plan').innerText(),/\[object Object\]|Ändert nur die Anzeigenamen/);
  assert.equal(await page.locator('#org-apply-names').count(),0);
  await page.locator('#org-plan').getByRole('button',{name:'Gespeicherten Planstatus laden',exact:true}).click();
  assert.equal((await command({action:'snapshot'})).label_creates,afterNew.label_creates);
  assert.deepEqual(errors,[]);
  console.log('ok 8 - metadata history uses its actual plan type, readable labels and correct read-only status route');
  await page.waitForFunction(()=>!window.PilotSuiteOrganization.dirty());
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  await page.locator(`[data-ps-zone="${savedSetup.zone_id}"]`).click();
  await page.waitForFunction(id=>selectionZone===id&&!selectionBusy,savedSetup.zone_id);
  await page.locator('.ps-zone-nav [data-ps-nav="zone"]').click();
  await page.locator('[data-setup-action="presence"]').click();
  await page.locator('#ps-zone-form').waitFor();
  assert.equal(await page.locator('#ps-zone-form .ps-zone-source-edit legend input:checked').count(),1,'confirmed source is prefilled');
  await page.getByRole('button',{name:'Verwerfen',exact:true}).click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  await page.locator(`[data-ps-zone="${savedSetup.zone_id}"]`).click();
  await page.waitForFunction(()=>!selectionBusy);
  await page.locator('.ps-zone-nav [data-ps-nav="zone"]').click();
  await page.locator('[data-setup-action="existing"]').click();
  await page.locator('#org-load').click();
  await page.locator('#org-zone-suggestions').waitFor();
  if(out)await page.locator('#org-zone-suggestions').screenshot({path:path.join(out,'zone-binding-proposal.png')});
  const beforeProposal=await page.evaluate(()=>json('api/v1/zones/'+encodeURIComponent(selectionZone)+'/organization'));
  await page.getByRole('button',{name:'Diese Zonenvorschläge vormerken',exact:true}).click();
  const afterProposal=await page.evaluate(()=>json('api/v1/zones/'+encodeURIComponent(selectionZone)+'/organization'));
  assert.deepEqual(afterProposal.bindings,beforeProposal.bindings,'prefill is an unsaved proposal');
  assert.equal(await page.locator('[data-org-role="presence_sources"][data-org-candidate="binary_sensor.demo_presence"]').getAttribute('aria-pressed'),'true');
  await page.locator('#org-save').click();
  await page.waitForFunction(()=>!window.PilotSuiteOrganization.dirty()&&document.querySelector('#org-message').textContent.includes('gespeichert'));
  const linkedSources=await page.evaluate(()=>json('api/v1/zones/'+encodeURIComponent(selectionZone)+'/organization'));
  assert.deepEqual(linkedSources.bindings.assignments.presence_sources.map(r=>r.entity_id),['binary_sensor.demo_presence']);
  const finalProposal=await command({action:'snapshot'});
  assert.equal(finalProposal.output_calls,afterNew.output_calls);
  assert.equal(finalProposal.helper_creates,afterNew.helper_creates);
  assert.deepEqual(errors,[]);
  console.log('ok 9 - setup journey opens existing editors; known sources prefill without save or control, one explicit mapping save');

  await page.locator('.ps-nav [data-ps-nav="cockpit"]').click();
  await page.locator('[data-ps-zone="room"]').click();await page.waitForFunction(()=>selectionZone==='room'&&!selectionBusy);
  await command({action:'light_group'});await page.evaluate(()=>loadSelection('room'));
  await command({action:'tick',values:{'binary_sensor.demo_presence':'on','binary_sensor.demo_motion':'off'}});await refreshPresence();
  const beforeLight=await command({action:'snapshot'});
  await page.locator('#ps-lighting-configure').click();
  await page.getByLabel('Tageslichtquelle',{exact:true}).selectOption('sensor.demo_lux');
  await page.getByLabel('Herkunft der Luxmessung',{exact:true}).selectOption('outdoor');
  await page.getByLabel('Pause nach Lichtänderung (s)',{exact:true}).fill('600');
  await page.getByLabel('Lichtgruppe Demo',{exact:true}).check();
  await page.getByRole('button',{name:'Lichtvergleich speichern',exact:true}).click();
  await page.getByText('Lichtgruppen und ihre Mitglieder überschneiden sich; nur einmal zuordnen',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('Lichtgruppe Demo',{exact:true}).isChecked(),true,'group conflict retains the draft');
  assert.equal(await page.getByLabel('Pause nach Lichtänderung (s)',{exact:true}).inputValue(),'600');
  await page.getByLabel('Lichtgruppe Demo',{exact:true}).uncheck();
  await page.evaluate(async()=>{await load({background:true});await load({background:true});});
  assert.equal(await page.getByLabel('Pause nach Lichtänderung (s)',{exact:true}).inputValue(),'600');
  await page.route('**/api/v1/zones/room/lighting',route=>route.fulfill({status:503,json:{message:'Synthetic light save failure'}}),{times:1});
  await page.getByRole('button',{name:'Lichtvergleich speichern',exact:true}).click();
  await page.getByText('Synthetic light save failure',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('Tageslichtquelle',{exact:true}).inputValue(),'sensor.demo_lux');
  if(out)for(const width of [390,1440]){await page.setViewportSize({width,height:1100});await page.locator('#ps-zone-lighting-form').screenshot({path:path.join(out,`zone-lighting-editor-${width}.png`)});}
  const lightDialogs=dialogCount;await page.getByRole('button',{name:'Lichtvergleich speichern',exact:true}).click();
  await page.waitForFunction(()=>!selectionBusy&&!window.PilotSuiteZonePresence.dirty());
  assert.equal(dialogCount,lightDialogs);
  for(let i=0;i<3;i++)await command({action:'tick',seconds:10});
  await refreshPresence();await page.locator('#ps-zone-lighting').getByText(/^Vorschlag:/).waitFor();
  const lightState=await page.evaluate(()=>json('api/v1/zones/room/presence'));
  assert.equal(lightState.lighting.current.presence_state,lightState.current.state);
  assert.equal(lightState.lighting.execution.allowed,false);
  assert.equal(lightState.lighting.spec.manual_hold_seconds,600);
  const afterLight=await command({action:'snapshot'});
  assert.equal(afterLight.output_calls,beforeLight.output_calls);assert.equal(afterLight.helper_creates,beforeLight.helper_creates);
  if(out)await page.locator('#ps-zone-lighting').screenshot({path:path.join(out,'zone-lighting-comparison.png')});
  assert.deepEqual(errors,[]);
  console.log('ok 10 - live light comparison shares primary presence; bounded settings, drafts/errors and no actuator calls');


 }finally{if(browser)await browser.close();proc.stdin.end();proc.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
